### ISSUE TITLE
Saved search records are not usable

### ISSUE THREAD

**Issue by omrilit** [oracle/netsuite-suitecloud-sdk#127]
When importing savedsearch records, their definition field is generated to a different value every run.
Is it on purpose? If so, why even expose it in the SDF project if the user can't read/edit it?

**Comment by colivares82** [comment]
Hello @omrilit ,  I am not 100% this is the only reason, but I think the value is different because the export includes some timestamp when is exposing the representation. At any case, this is something that we can not control in the tools. 
Since this is something that is outside of our scope, I will close the issue.
