### ISSUE TITLE
setupaccount task fails if password contains a bracket "("

### ISSUE THREAD

**Issue by stevegoldberg** [oracle/netsuite-suitecloud-sdk#23]
Requirements: Have a user account set up where the user's password contains a bracket (aka parenthesis).

STR: 
1. Run `suitecloud setupaccount`
2. When prompted with `Do you want to issue or save a TBA token?`, select `Issue a token`.

Expected result: the wizard continues normally

Actual result: an error is returned: `/bin/sh: -c: line 0: syntax error near unexpected token '('`

Full log:
```
MacBook-Pro:MyFirstCommerceExtension sgoldberg-oracle$ suitecloud setupaccount
? Enter your email: myemail@netsuite.com
? Enter your password: [hidden]
? Select the account ID: SuiteCommerce - [Administrator]
? Do you want to issue or save a TBA token?
    If your role requires 2FA, you must save a TBA token issued in NetSuite. To learn how to issue a toke
n in NetSuite, see https://system.netsuite.com/app/help/helpcenter.nl?fid=bridgehead_4254083671.html. Iss
ue a TBA token.
ERROR: SDK exited with code 2
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `java -jar  -DintegrationMode  -DclientPlatformVersion=10.16.3 "/Users/sgoldberg 1/netsuite-suitecloud-node-cli/bin/cli-2019.2.1.jar" issuetoken -password mypasswordhasabracketinit( -account TSTDRV1234567893 -role 3 -email myemail@netsuite.com -url tstdrv123456789.restlets.api.netsuite.com '
```

(Some details have been obscured. Note that it dumps your password in your terminal window.)

**Comment by margabit** [comment]
Thanks for reporting this, Steve!
We are implementing a new authentication flow for the next major release that will not require users to input the password in the CLI. Instead, the user will setup the account using browser-based authentication (oAuth). The `dev` branch has the new implementation already. 
Then, this problem should be resolved for the Node.js CLI in the next major release, planned for February/March 2020.

Since this bug is at the SDK level (Java Jar), we should still fix it for other commands that require password in the Java-based CLI (for instance, issuetoken).

**Comment by vic-nik** [comment]
Hello Steve @stevegoldberg,
Thank you for your feedback!
I understand you are using the code from master branch that has code for 19.2 version which was not officially released, this code is outdated, all active development happens in /dev branch.
We will officially release 20.1 version of suitecloud-cli in npmjs.com in the following weeks, the latest code will be merged into master then.
If you would like to use suitecloud-cli already I would recommend installing from /dev branch.
Closing this issue as outdated.
