### ISSUE TITLE
Remaining N/Module Stubs to be provided.

### ISSUE THREAD

**Issue by karl-roberson-infinet** [oracle/netsuite-suitecloud-sdk#466]
### Expected Behavior
That tests will go smoothly without having to create standard netsuite stubs that should be provided.

**Comment by zatloeri** [comment]
I second this. This would be very much appreciated.

**Comment by colivares82** [comment]
Hello @karl-roberson-infinet  and @zatloeri,

We have heard this and we understand is really helpful to have the whole SuiteScript API Stub Definitions, however, due to the team capacity and other elements we are pursuing for the whole community we can not provide a commitment to deliver this anytime soon.  

The custom stub configuration, for now, I think will be the best option for everyone to follow, maybe it could even exist an open-source SuiteScript API Stub repo that accepts contributions that we are not aware of, and organically generate this type of offerings for the community (I don't have knowledge about the existence of such thing).
