### ISSUE TITLE
Inactive Roles do not trigger failures during project:validate or project:deploy --dryrun

### ISSUE THREAD

**Issue by ericgrubaughcompass** [oracle/netsuite-suitecloud-sdk#646]
### Your environment
**OS** : Ubuntu 22.04
**Node.js version** : 18.8
**suitecloud-cli version** : 1.6.2
**Terminal/CMD tool** : Bash shell

### Describe the bug
If an SDF project references a Role which has been inactivated, whether the reference is in the manifest or in an Object definition, this will cause the `project:deploy` command to (correctly) fail with an `Invalid Reference` error. However, the error *will not* be thrown by either the `project:validate` command or if the `--dryrun` switch is used with the `project:deploy` command, causing a false-positive result from these commands.

If `project:deploy` fails when the project references an inactive Role, then both `project:validate` and `project:deploy --dryrun` should fail in a similar manner.

### To Reproduce
1. Create or locate a Role for testing purposes.
3. Inactivate the Role.
4. Add the inactivated Role as a dependency in your SDF project's `manifest.xml` file.
5. [Optional] Add a reference to the inactivated Role to the permissions list of any Object(s) in your project.
6. Run `project:validate --server`. Observe success.
7. Run `project:deploy --dryrun`. Observe success.
8. Run `project:deploy`. Observe failure "Invalid Reference" error.

### Actual Behavior
* `project:validate` succeeds.
* `project:deploy --dryrun` succeeds.
* `project:deploy` fails with "Invalid Reference" error.

### Expected Behavior
* `project:validate` fails with "Invalid Reference" error.
* `project:deploy --dryrun` fails with "Invalid Reference" error.
* `project:deploy` fails with "Invalid Reference" error.

### Additional context
In order to be reliable tools for deployment, `project:validate` and `project:deploy --dryrun` must behave as identical to `project:deploy` as possible.

**Comment by lfpvillegas** [comment]
Hi @ericgrubaughcompass 
We are currently reviewing past issues.
I am not able to replicate the issue right now. I have been able to deploy an inactivated role referenced both in the manifest and in another object.

I'm closing the issue since it seems it has been already fixed.
If you still experience a similar problem, please reopen this ticket and provide us some example files.

Thanks

**Comment by ball-of-twine** [comment]
Hi @lfpvillegas,
I think there's some confusion around what the issue is. It was not about being able to deploy an inactive role, but about referencing the inactive role and getting false-positive validate/dry-run results.

I was able to reproduce the issue by following the replication steps. However, I found that step 5 was not optional. Here are some test files that can be dropped into a new SDF project (uploaded here as .xml.txt, as [.xml is unsupported in comments](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files#:~:text=We%20support%20these%20files%3A))

[customrecord_test.xml](https://github.com/oracle/netsuite-suitecloud-sdk/files/14273767/customrecord_test.xml.txt)
[manifest.xml](https://github.com/oracle/netsuite-suitecloud-sdk/files/14273757/manifest.xml.txt)
[customrole_inactive.xml.txt](https://github.com/oracle/netsuite-suitecloud-sdk/files/14273759/customrole_inactive.xml) (example inactive role. To be added to the account, but not to actually be included in SDF project)

**Comment by lfpvillegas** [comment]
Hi @ball-of-twine . 
Thanks for your message and extra info.
There has not been any misunderstanding. I have closed the issue because I was able to deploy an inactive role, so the disparity between deploy and validate/dry-run was not there. As you noted, this didn't include the optional step.

However, with your files (and some extra tweaks ) I have been able to reproduce the error.
I have also noted that executing project:validate --server command it's also passing fine. This is important because there is no disparity between local and server validation, but only with project:deploy.

Nevertheless, the issue ticket would remain closed because this issue is not directly related to the CLI, but with the server validation, which is not handled in this Github repository.

Please fill a Customer Service Support ticket, sot his issue could reach the team responsible of this feature and you could receive updates on it.

Thanks,
