### ISSUE TITLE
OSx - Before executing any SuiteCloud command, SuiteCloud SDK dependencies need to be validated. Try again in a few seconds.

### ISSUE THREAD

**Issue by ekloneleuterio** [oracle/netsuite-suitecloud-sdk#662]
Hello guys!

I'm trying to use the VSCode Extension with OSX, but I'm not able to it:
The warning "Before executing any SuiteCloud command, SuiteCloud SDK dependencies need to be validated. Try again in a few seconds."

We have another closed thread related to it, but without solution.

Please, could you help with that?

_Originally posted by @ekloneleuterio in https://github.com/oracle/netsuite-suitecloud-sdk/issues/470#issuecomment-1353303316_

**Comment by ekloneleuterio** [comment]
<img width="457" alt="image" src="https://user-images.githubusercontent.com/96245681/210245273-eee60685-0f58-4468-a230-ee28275d7d57.png">
Warning message

**Comment by alii-gator** [comment]
@ekloneleuterio Are you behind any proxy?
Which OSX version do you have?
Version of VSCode?

**Comment by alii-gator** [comment]
@ekloneleuterio Can we have a quick screen sharing session to determine what's causing this?

**Comment by gustavodona** [comment]
I'm having the same issue

**Comment by ekloneleuterio** [comment]
> @ekloneleuterio Are you behind any proxy? Which OSX version do you have? Version of VSCode?

Hi @alii-gator ! 
No, I'm not behind any proxy. 

I'm using MacOs Ventura 13.1
VsCode Version: 1.74.2 (Universal).

And yes, we also can have a screen sharing  . Thanks!

**Comment by pmannion2** [comment]
Unfortunately I am in the same boat! No proxy, Ventura 13.4, VSC 1.81.1 (universal)

**Comment by eklonsousa** [comment]
Hello guys,

Please, double-check if your node is globally installed.

I had to reinstall it and set it as global

`npm config set prefix '~/.npm-global'`

**Comment by davidecorreu** [comment]
### Possible problem source
If your `~/.sutiecloud-sdk` is owned by the root user, instead of your user, **SuiteCloud Extension for Visual Studio Code** won't be capable of storing the SutieCloud SDK dependencies properly, leading to original problem.
If that's the case, one possible solution is to change the ownership of the `~/.suitecloud-sdk` folder to your user.

### Possible problem origin
If at some point you have installed our **SuiteCloud CLI for Node.js** using `sudo` , there will be some permission problems later with the installation process of **SuiteCloud Extension for Visual Studio Code**.

The source reason is that your `~/.suitecloud-sdk` folder will be owned by the root user if you did run `sudo npm install -g @oracle/suitecloud-cli`.

In order to avoid using `sudo` to install **SuiteCloud CLI for Node.js**, you can use @eklonsousa suggestion before performing the global npm installation.
So you could do:
 1.  `npm config set prefix '~/.npm-global'`
 2.  `npm install -g @oracle/suitecloud-cli`
