### ISSUE TITLE
getting a null pointer error when deploying project to account

### ISSUE THREAD

**Issue by timothy-o-johnson** [oracle/netsuite-suitecloud-sdk#88]
Does moving the project files into the 'src' folder in step two impact how the project is deployed?

I'm getting the following error:

'!MESSAGE Internal error encountered (Null pointer exception).'

**Comment by alii-gator** [comment]
@timothy-o-johnson All your suitecloud project files should be under src folder. You can create a project by the cli and see the project structure created, then you can convert any of your old projects according to the same project structure if this is what you are trying to do.
src folder is set as your default project root, which can be changed in suitecloud.config.js
But any how can you provide detailed steps on how you are getting "Null pointer exception"?

**Comment by timothy-o-johnson** [comment]
wow, thanks for the prompt response @alii-gator . i'm actually using the SDF to deploy to my account. i'm right clicking the it doesn't provide much info for the error. I'll send an image of how it's laid out and a reading of the log. 

Here's what I click:
![image](https://user-images.githubusercontent.com/13969159/78685542-7ece0280-78b7-11ea-9244-a0c4389107a9.png)

Here's the error:
![image](https://user-images.githubusercontent.com/13969159/78685604-960cf000-78b7-11ea-9a72-2c458338aa6f.png)

Here's the folder structure:
![image](https://user-images.githubusercontent.com/13969159/78685277-24cd3d00-78b7-11ea-8d3d-eba0bfb3486d.png)

I was considering clearing the repository and starting again.  The suitecloud.config.js has 'src' as the root.

Again, really appreciate the help!

**Comment by alii-gator** [comment]
@timothy-o-johnson Actually disregard what i said, Since this space if for suitecloud CLI for NodeJS, i assumed you were getting NPE while using this. 
Apparently you are using Eclipse. I will suggest you to use NodeCLI or if you preffer IDE you can try WebStorm plugin of Suitecloud.

If you want to use Eclipse, the supported version is Mars 2, and open the project where "src" is root, so you have manifest and deploy.xml under root, then try to deploy.
Eclipse doesnt support the project structure you have right now. 
SuiteCloud plugin for Webstorm and SUiteCloud cli for NodeJS do support the project structure you have.

**Comment by timothy-o-johnson** [comment]
Excellent! Again thanks for the prompt reply. I'll give this ideas a shot.  Thank you!

**Comment by MrRob** [comment]
@timothy-o-johnson Hey, I was curious if you ever figured this out.  I'm running into the same problem trying to deploy/validate one of my SuiteApps in Eclipse

**Comment by edamazzio** [comment]
In case someone ever gets this null pointer exception in WebStorms (or I guess in CLI for Node as well), and you use special characters in your files/folders, like ó, ö, etc., then don't. I renamed files with such characters and that fixed the NPE.
